import { __String } from "typescript";

export interface I_User {
  id: string;
  userName: string;
  email: string;
  fullname: string | "";
  status: boolean;
  password: string;
  role: boolean;
  avatar?: string | "";
  phone: string | "";
  address: string | "";
  created_at: string;
  updated_at: string;
  myCourses: any[];
};

// export const users: I_User[] = [
//   {
//     user_id: 1,
//     username: "user1",
//     email: "user1@example.com",
//     fullname: "User One",
//     status: true,
//     password: "hashed_password1",
//     role: false,
//     avatar: "avatar1.jpg",
//     phone: "1234567890",
//     address: "123 Street One, City One",
//     created_at: "01/10/2023",
//     updated_at: "01/10/2023",
//     myCourses: [],
//   },
//   {
//     user_id: 2,
//     username: "user2",
//     email: "user2@example.com",
//     fullname: "User Two",
//     status: false,
//     password: "hashed_password2",
//     role: false,
//     avatar: "avatar2.jpg",
//     phone: "2345678901",
//     address: "456 Street Two, City Two",
//     created_at: "02/10/2023",
//     updated_at: "02/10/2023",
//     myCourses: [],
//   },
//   {
//     user_id: 3,
//     username: "user3",
//     email: "user3@example.com",
//     fullname: "User Three",
//     status: false,
//     password: "hashed_password3",
//     role: false,
//     avatar: "avatar3.jpg",
//     phone: "3456789012",
//     address: "789 Street Three, City Three",
//     created_at: "03/10/2023",
//     updated_at: "03/10/2023",
//     myCourses: [],
//   },
//   {
//     user_id: 4,
//     username: "user4",
//     email: "user4@example.com",
//     fullname: "User Four",
//     status: false,
//     password: "hashed_password4",
//     role: false,
//     avatar: "avatar4.jpg",
//     phone: "4567890123",
//     address: "101 Street Four, City Four",
//     created_at: "04/10/2023",
//     updated_at: "04/10/2023",
//     myCourses: [],
//   },
//   {
//     user_id: 5,
//     username: "user5",
//     email: "user5@example.com",
//     fullname: "User Five",
//     status: true,
//     password: "hashed_password5",
//     role: false,
//     avatar: "avatar5.jpg",
//     phone: "5678901234",
//     address: "202 Street Five, City Five",
//     created_at: "05/10/2023",
//     updated_at: "05/10/2023",
//     myCourses: [],
//   },
//   {
//     user_id: 6,
//     username: "user6",
//     email: "user6@example.com",
//     fullname: "User Six",
//     status: true,
//     password: "hashed_password6",
//     role: false,
//     avatar: "avatar6.jpg",
//     phone: "6789012345",
//     address: "303 Street Six, City Six",
//     created_at: "06/10/2023",
//     updated_at: "06/10/2023",
//     myCourses: [],
//   },
//   {
//     user_id: 7,
//     username: "user7",
//     email: "user7@example.com",
//     fullname: "User Seven",
//     status: true,
//     password: "hashed_password7",
//     role: false,
//     avatar: "avatar7.jpg",
//     phone: "7890123456",
//     address: "404 Street Seven, City Seven",
//     created_at: "07/10/2023",
//     updated_at: "07/10/2023",
//     myCourses: [],
//   },
//   {
//     user_id: 8,
//     username: "user8",
//     email: "user8@example.com",
//     fullname: "User Eight",
//     status: true,
//     password: "hashed_password8",
//     role: false,
//     avatar: "avatar8.jpg",
//     phone: "8901234567",
//     address: "505 Street Eight, City Eight",
//     created_at: "08/10/2023",
//     updated_at: "08/10/2023",
//     myCourses: [],
//   },
//   {
//     user_id: 9,
//     username: "user9",
//     email: "user9@example.com",
//     fullname: "User Nine",
//     status: true,
//     password: "hashed_password9",
//     role: false,
//     avatar: "avatar9.jpg",
//     phone: "9012345678",
//     address: "606 Street Nine, City Nine",
//     created_at: "09/10/2023",
//     updated_at: "09/10/2023",
//     myCourses: [],
//   },
//   {
//     user_id: 10,
//     username: "user10",
//     email: "user10@example.com",
//     fullname: "User Ten",
//     status: true,
//     password: "hashed_password10",
//     role: false,
//     avatar: "avatar10.jpg",
//     phone: "0123456789",
//     address: "707 Street Ten, City Ten",
//     created_at: "10/10/2023",
//     updated_at: "10/10/2023",
//     myCourses: [],
//   },
// ];


